from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('transactions/', views.transactions_view, name='transactions'),
    path('budgets/', views.budgets_view, name='budgets'),
    path('budgets/add/', views.add_budget, name='add_budget'),
    path('budgets/<int:budget_id>/edit/', views.edit_budget, name='edit_budget'),
    path('budgets/<int:budget_id>/delete/', views.delete_budget, name='delete_budget'),
    path('bills/', views.bills_view, name='bills'),
    path('reports/', views.reports_view, name='reports'),
    path('settings/', views.settings_view, name='settings'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('onboarding/step1/', views.onboarding_step1, name='onboarding_step1'),
    path('onboarding/step2/', views.onboarding_step2, name='onboarding_step2'),
    path('onboarding/step3/', views.onboarding_step3, name='onboarding_step3'),
    path('onboarding/step4/', views.onboarding_step4, name='onboarding_step4'),
    path('onboarding/step5/', views.onboarding_step5, name='onboarding_step5'),
    path('onboarding/step6/', views.onboarding_step6, name='onboarding_step6'),
    path('accounts/', views.accounts_view, name='accounts'),
    path('accounts/add/', views.add_account, name='add_account'),
    path('accounts/<int:account_id>/edit/', views.edit_account, name='edit_account'),
    path('accounts/<int:account_id>/delete/', views.delete_account, name='delete_account'),
    path('transactions/add/', views.add_transaction, name='add_transaction'),
    path('transactions/<int:transaction_id>/delete/', views.delete_transaction, name='delete_transaction'),
    path('bills/add/', views.add_bill, name='add_bill'),
    path('bills/<int:bill_id>/delete/', views.delete_bill, name='delete_bill'),
    path('bills/<int:bill_id>/pay/', views.start_bill_payment, name='start_bill_payment'),
    path('transactions/export/', views.export_transactions, name='export_transactions'),
    path('payments/<str:merchant_order_id>/', views.payment_status, name='payment_status'),
    path('payments/<str:merchant_order_id>/receipt/', views.download_receipt, name='download_receipt'),
    path('payments/phonepe/webhook/', views.phonepe_webhook, name='phonepe_webhook'),
]
